# Generated by Django 5.1.3 on 2024-11-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
