# Generated by Django 5.1.3 on 2024-11-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_document_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_id',
        ),
    ]
