# Generated by Django 4.2 on 2024-10-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0002_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dean.program'),
        ),
    ]
